Resources:
  webSgfromdev3TierAutoScalingappInstanceSecurityGroup2115526E543217CD4C37:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from dev3TierAutoScalingappInstanceSecurityGroup2115526E:5432
      FromPort: 5432
      GroupId:
        Fn::ImportValue: dev-3Tier-DB:ExportsOutputFnGetAttdbsgCE6973BDGroupIdACE24D8F
      SourceSecurityGroupId:
        Fn::GetAtt:
          - appInstanceSecurityGroup2A99D910
          - GroupId
      ToPort: 5432
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/webSg/from
        dev3TierAutoScalingappInstanceSecurityGroup2115526E:5432
  websgC669AD03:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dev-3Tier-AutoScaling/web-sg
      GroupName: dev-3Tier-web-sg
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow from anyone on port 80
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      Tags:
        - Key: Name
          Value: dev-3Tier-web-sg
      VpcId:
        Fn::ImportValue: dev-3Tier-Network:VPCVpcId2F75874A
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/web-sg/Resource
  dev3TierinternetC5AC4D78:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        []
      Name: dev-3Tier-internet
      Scheme: internet-facing
      SecurityGroups:
        - Fn::GetAtt:
            - websgC669AD03
            - GroupId
      Subnets:
        - Fn::Select:
            - 0
            - Fn::Split:
                - ","
                - Fn::ImportValue: dev-3Tier-Network:VPCPublicSubnetIDs428979F9
        - Fn::Select:
            - 1
            - Fn::Split:
                - ","
                - Fn::ImportValue: dev-3Tier-Network:VPCPublicSubnetIDs428979F9
      Type: application
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/dev-3Tier-internet/Resource
  dev3Tierinternetlistener34129503:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: webtg8CFB297D
          Type: forward
      LoadBalancerArn:
        Ref: dev3TierinternetC5AC4D78
      Port: 80
      Protocol: HTTP
      Certificates:
        []
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/dev-3Tier-internet/listener/Resource
  webtg8CFB297D:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId:
        Fn::ImportValue: dev-3Tier-Network:VPCVpcId2F75874A
      TargetGroupAttributes:
        []
      Targets:
        []
      TargetType: instance
      Name: dev-3Tier-web-tg
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/web-tg/Resource
  webInstanceSecurityGroupA26AA3C5:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dev-3Tier-AutoScaling/web/InstanceSecurityGroup
      GroupName: dev-3Tier-dev-3Tier-web-asg
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        []
      Tags:
        - Key: Name
          Value: dev-3Tier-AutoScaling/web
      VpcId:
        Fn::ImportValue: dev-3Tier-Network:VPCVpcId2F75874A
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/web/InstanceSecurityGroup/Resource
  webInstanceSecurityGroupfromdev3TierAutoScalingwebsg27540E4A80071F5E75:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: Load balancer to target
      FromPort: 80
      GroupId:
        Fn::GetAtt:
          - webInstanceSecurityGroupA26AA3C5
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - websgC669AD03
          - GroupId
      ToPort: 80
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/web/InstanceSecurityGroup/from
        dev3TierAutoScalingwebsg27540E4A:80
  webInstanceRole18A3CFAB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/web/InstanceRole/Resource
  webInstanceProfile7CBE575C:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: webInstanceRole18A3CFAB
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/web/InstanceProfile
  webLaunchConfig014FA60D:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-00a5245b4816c38e6
      InstanceType: t2.micro
      IamInstanceProfile:
        Ref: webInstanceProfile7CBE575C
      SecurityGroups:
        - Fn::GetAtt:
            - webInstanceSecurityGroupA26AA3C5
            - GroupId
      UserData:
        Fn::Base64: |
          #!/bin/bash
      LaunchConfigurationName: dev-3Tier-web-config
    DependsOn:
      - webInstanceRole18A3CFAB
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/web/LaunchConfig
  webASG4A8B8025:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: "4"
      MinSize: "0"
      DesiredCapacity: "2"
      LaunchConfigurationName:
        Ref: webLaunchConfig014FA60D
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: dev-3Tier-AutoScaling/web
      TargetGroupARNs:
        - Ref: webtg8CFB297D
      VPCZoneIdentifier:
        - Fn::Select:
            - 0
            - Fn::Split:
                - ","
                - Fn::ImportValue: dev-3Tier-Network:VPCPublicSubnetIDs428979F9
        - Fn::Select:
            - 1
            - Fn::Split:
                - ","
                - Fn::ImportValue: dev-3Tier-Network:VPCPublicSubnetIDs428979F9
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/web/ASG
  appInstanceSecurityGroup2A99D910:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dev-3Tier-AutoScaling/app/InstanceSecurityGroup
      GroupName: dev-3Tier-dev-3Tier-app-asg
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        []
      Tags:
        - Key: Name
          Value: dev-3Tier-AutoScaling/app
      VpcId:
        Fn::ImportValue: dev-3Tier-Network:VPCVpcId2F75874A
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/app/InstanceSecurityGroup/Resource
  appInstanceSecurityGroupfromdev3TierAutoScalingappsgE9D313CB8080530EC3AA:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: Load balancer to target
      FromPort: 8080
      GroupId:
        Fn::GetAtt:
          - appInstanceSecurityGroup2A99D910
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - appsg42805CE6
          - GroupId
      ToPort: 8080
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/app/InstanceSecurityGroup/from
        dev3TierAutoScalingappsgE9D313CB:8080
  appInstanceRoleDA866B93:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/app/InstanceRole/Resource
  appInstanceProfileF452F4E3:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: appInstanceRoleDA866B93
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/app/InstanceProfile
  appLaunchConfigA16ECF23:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-00a5245b4816c38e6
      InstanceType: t2.micro
      IamInstanceProfile:
        Ref: appInstanceProfileF452F4E3
      SecurityGroups:
        - Fn::GetAtt:
            - appInstanceSecurityGroup2A99D910
            - GroupId
      UserData:
        Fn::Base64: |
          #!/bin/bash
      LaunchConfigurationName: dev-3Tier-app-config
    DependsOn:
      - appInstanceRoleDA866B93
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/app/LaunchConfig
  appASG5BBEB5D4:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: "4"
      MinSize: "0"
      DesiredCapacity: "2"
      LaunchConfigurationName:
        Ref: appLaunchConfigA16ECF23
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: dev-3Tier-AutoScaling/app
      TargetGroupARNs:
        - Ref: apptgF4E769B4
      VPCZoneIdentifier:
        - Fn::Select:
            - 2
            - Fn::Split:
                - ","
                - Fn::ImportValue: dev-3Tier-Network:VPCPublicSubnetIDs428979F9
        - Fn::Select:
            - 3
            - Fn::Split:
                - ","
                - Fn::ImportValue: dev-3Tier-Network:VPCPublicSubnetIDs428979F9
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/app/ASG
  appsg42805CE6:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dev-3Tier-AutoScaling/app-sg
      GroupName: dev-3Tier-app-sg
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow from anyone on port 8080
          FromPort: 8080
          IpProtocol: tcp
          ToPort: 8080
      Tags:
        - Key: Name
          Value: dev-3Tier-app-sg
      VpcId:
        Fn::ImportValue: dev-3Tier-Network:VPCVpcId2F75874A
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/app-sg/Resource
  appsgfromdev3TierAutoScalingwebInstanceSecurityGroup1F4D1D228080596CD2F3:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from dev3TierAutoScalingwebInstanceSecurityGroup1F4D1D22:8080
      FromPort: 8080
      GroupId:
        Fn::GetAtt:
          - appsg42805CE6
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - webInstanceSecurityGroupA26AA3C5
          - GroupId
      ToPort: 8080
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/app-sg/from
        dev3TierAutoScalingwebInstanceSecurityGroup1F4D1D22:8080
  dev3TierinternalF413AEF5:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        []
      Name: dev-3Tier-internal
      Scheme: internal
      SecurityGroups:
        - Fn::GetAtt:
            - appsg42805CE6
            - GroupId
      Subnets:
        - Fn::Select:
            - 2
            - Fn::Split:
                - ","
                - Fn::ImportValue: dev-3Tier-Network:VPCPublicSubnetIDs428979F9
        - Fn::Select:
            - 3
            - Fn::Split:
                - ","
                - Fn::ImportValue: dev-3Tier-Network:VPCPublicSubnetIDs428979F9
      Type: application
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/dev-3Tier-internal/Resource
  dev3Tierinternallistener07E2D1FD:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: apptgF4E769B4
          Type: forward
      LoadBalancerArn:
        Ref: dev3TierinternalF413AEF5
      Port: 8080
      Protocol: HTTP
      Certificates:
        []
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/dev-3Tier-internal/listener/Resource
  apptgF4E769B4:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 8080
      Protocol: HTTP
      VpcId:
        Fn::ImportValue: dev-3Tier-Network:VPCVpcId2F75874A
      TargetGroupAttributes:
        []
      Targets:
        []
      TargetType: instance
      Name: dev-3Tier-app-tg
    Metadata:
      aws:cdk:path: dev-3Tier-AutoScaling/app-tg/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.22.0,@aws-cdk/aws-autoscaling=0.22.0,@aws-cdk/aws-autoscaling-common=0.22.0,@aws-cdk/aws-cloudwatch=0.22.0,@aws-cdk/aws-codedeploy-api=0.22.0,@aws-cdk/aws-ec2=0.22.0,@aws-cdk/aws-elasticloadbalancingv2=0.22.0,@aws-cdk/aws-iam=0.22.0,@aws-cdk/aws-rds=0.22.0,@aws-cdk/cdk=0.22.0,@aws-cdk/cx-api=0.22.0,jsii-runtime=node.js/v10.14.1
