Resources:
  dev3TierdbB46B52AD:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dev-3Tier-DB/dev-3Tier-db
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        []
      Tags:
        - Key: Name
          Value: dev-3Tier-db
      VpcId:
        Fn::ImportValue: dev-3Tier-Web:VPCVpcId2F75874A
    Metadata:
      aws:cdk:path: dev-3Tier-DB/dev-3Tier-db/Resource
  dev3Tierdbfromdev3TierDBappSgF396B4085432B7E6F427:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from dev3TierDBappSgF396B408:5432
      FromPort: 5432
      GroupId:
        Fn::GetAtt:
          - dev3TierdbB46B52AD
          - GroupId
      SourceSecurityGroupId:
        Fn::ImportValue: dev-3Tier-App:dev3TierappSecurityGroupId8ADD0104
      ToPort: 5432
    Metadata:
      aws:cdk:path: dev-3Tier-DB/dev-3Tier-db/from dev3TierDBappSgF396B408:5432
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.21.0,@aws-cdk/assets=0.21.0,@aws-cdk/aws-autoscaling=0.21.0,@aws-cdk/aws-autoscaling-common=0.21.0,@aws-cdk/aws-cloudformation=0.21.0,@aws-cdk/aws-cloudfront=0.21.0,@aws-cdk/aws-cloudwatch=0.21.0,@aws-cdk/aws-codedeploy-api=0.21.0,@aws-cdk/aws-codepipeline-api=0.21.0,@aws-cdk/aws-ec2=0.21.0,@aws-cdk/aws-elasticloadbalancingv2=0.21.0,@aws-cdk/aws-events=0.21.0,@aws-cdk/aws-iam=0.21.0,@aws-cdk/aws-kms=0.21.0,@aws-cdk/aws-lambda=0.21.0,@aws-cdk/aws-s3=0.21.0,@aws-cdk/aws-s3-deployment=0.21.0,@aws-cdk/aws-s3-notifications=0.21.0,@aws-cdk/aws-sqs=0.21.0,@aws-cdk/cdk=0.21.0,@aws-cdk/cx-api=0.21.0,jsii-runtime=node.js/v10.14.1
