Resources:
  VPCB9E5F0B4:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.101.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: 3tier-vpc
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/Resource
  VPCwebSubnet1Subnet70A8869C:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.101.0.0/24
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/webSubnet1
        - Key: aws-cdk:subnet-name
          Value: web
        - Key: aws-cdk:subnet-type
          Value: Public
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/webSubnet1/Subnet
  VPCwebSubnet1RouteTableD23956C7:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/webSubnet1
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/webSubnet1/RouteTable
  VPCwebSubnet1RouteTableAssociationCFDC03B8:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCwebSubnet1RouteTableD23956C7
      SubnetId:
        Ref: VPCwebSubnet1Subnet70A8869C
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/webSubnet1/RouteTableAssociation
  VPCwebSubnet1DefaultRoute17F2445C:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: VPCwebSubnet1RouteTableD23956C7
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: VPCIGWB7E252D3
    DependsOn:
      - VPCVPCGW99B986DC
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/webSubnet1/DefaultRoute
  VPCwebSubnet2SubnetA89FD16F:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.101.1.0/24
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/webSubnet2
        - Key: aws-cdk:subnet-name
          Value: web
        - Key: aws-cdk:subnet-type
          Value: Public
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/webSubnet2/Subnet
  VPCwebSubnet2RouteTable1443ACF4:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/webSubnet2
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/webSubnet2/RouteTable
  VPCwebSubnet2RouteTableAssociation130CDB9B:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCwebSubnet2RouteTable1443ACF4
      SubnetId:
        Ref: VPCwebSubnet2SubnetA89FD16F
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/webSubnet2/RouteTableAssociation
  VPCwebSubnet2DefaultRoute7C30D458:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: VPCwebSubnet2RouteTable1443ACF4
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: VPCIGWB7E252D3
    DependsOn:
      - VPCVPCGW99B986DC
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/webSubnet2/DefaultRoute
  VPCappSubnet1SubnetCDCE8516:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.101.2.0/24
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/appSubnet1
        - Key: aws-cdk:subnet-name
          Value: app
        - Key: aws-cdk:subnet-type
          Value: Private
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/appSubnet1/Subnet
  VPCappSubnet1RouteTable625B8824:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/appSubnet1
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/appSubnet1/RouteTable
  VPCappSubnet1RouteTableAssociation6E59FCF1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCappSubnet1RouteTable625B8824
      SubnetId:
        Ref: VPCappSubnet1SubnetCDCE8516
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/appSubnet1/RouteTableAssociation
  VPCappSubnet1DefaultRoute54E51750:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: VPCappSubnet1RouteTable625B8824
      DestinationCidrBlock: 0.0.0.0/0
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/appSubnet1/DefaultRoute
  VPCappSubnet2Subnet12EE3759:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.101.3.0/24
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/appSubnet2
        - Key: aws-cdk:subnet-name
          Value: app
        - Key: aws-cdk:subnet-type
          Value: Private
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/appSubnet2/Subnet
  VPCappSubnet2RouteTable86E30F77:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/appSubnet2
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/appSubnet2/RouteTable
  VPCappSubnet2RouteTableAssociationF764FEC2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCappSubnet2RouteTable86E30F77
      SubnetId:
        Ref: VPCappSubnet2Subnet12EE3759
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/appSubnet2/RouteTableAssociation
  VPCappSubnet2DefaultRoute8053AE9F:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: VPCappSubnet2RouteTable86E30F77
      DestinationCidrBlock: 0.0.0.0/0
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/appSubnet2/DefaultRoute
  VPCdbSubnet1SubnetC7C1BE50:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.101.4.0/24
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/dbSubnet1
        - Key: aws-cdk:subnet-type
          Value: Isolated
        - Key: aws-cdk:subnet-name
          Value: db
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/dbSubnet1/Subnet
  VPCdbSubnet1RouteTableFFCDD51A:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/dbSubnet1
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/dbSubnet1/RouteTable
  VPCdbSubnet1RouteTableAssociation873FD6F3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCdbSubnet1RouteTableFFCDD51A
      SubnetId:
        Ref: VPCdbSubnet1SubnetC7C1BE50
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/dbSubnet1/RouteTableAssociation
  VPCdbSubnet2Subnet4D0CD5E3:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.101.5.0/24
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/dbSubnet2
        - Key: aws-cdk:subnet-type
          Value: Isolated
        - Key: aws-cdk:subnet-name
          Value: db
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/dbSubnet2/Subnet
  VPCdbSubnet2RouteTableDE1713DD:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: dev-3Tier-Network/VPC/dbSubnet2
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/dbSubnet2/RouteTable
  VPCdbSubnet2RouteTableAssociation58734109:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCdbSubnet2RouteTableDE1713DD
      SubnetId:
        Ref: VPCdbSubnet2Subnet4D0CD5E3
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/dbSubnet2/RouteTableAssociation
  VPCIGWB7E252D3:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: 3tier-vpc
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/IGW
  VPCVPCGW99B986DC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      InternetGatewayId:
        Ref: VPCIGWB7E252D3
    Metadata:
      aws:cdk:path: dev-3Tier-Network/VPC/VPCGW
  dev3TierinternetC5AC4D78:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dev-3Tier-Network/dev-3Tier-internet
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: from 0.0.0.0/0:80
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      Tags:
        - Key: Name
          Value: dev-3Tier-internet
      VpcId:
        Ref: VPCB9E5F0B4
    Metadata:
      aws:cdk:path: dev-3Tier-Network/dev-3Tier-internet/Resource
  dev3Tierweb3038E85D:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dev-3Tier-Network/dev-3Tier-web
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        []
      Tags:
        - Key: Name
          Value: dev-3Tier-web
      VpcId:
        Ref: VPCB9E5F0B4
    Metadata:
      aws:cdk:path: dev-3Tier-Network/dev-3Tier-web/Resource
  dev3Tierwebfromdev3TierNetworkdev3Tierinternet3506845D804043209B:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from dev3TierNetworkdev3Tierinternet3506845D:80
      FromPort: 80
      GroupId:
        Fn::GetAtt:
          - dev3Tierweb3038E85D
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - dev3TierinternetC5AC4D78
          - GroupId
      ToPort: 80
    Metadata:
      aws:cdk:path: dev-3Tier-Network/dev-3Tier-web/from
        dev3TierNetworkdev3Tierinternet3506845D:80
  dev3TierinternalF413AEF5:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dev-3Tier-Network/dev-3Tier-internal
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: from 0.0.0.0/0:8080
          FromPort: 8080
          IpProtocol: tcp
          ToPort: 8080
      Tags:
        - Key: Name
          Value: dev-3Tier-internal
      VpcId:
        Ref: VPCB9E5F0B4
    Metadata:
      aws:cdk:path: dev-3Tier-Network/dev-3Tier-internal/Resource
  dev3TierappB3CC3F8F:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dev-3Tier-Network/dev-3Tier-app
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        []
      Tags:
        - Key: Name
          Value: dev-3Tier-app
      VpcId:
        Ref: VPCB9E5F0B4
    Metadata:
      aws:cdk:path: dev-3Tier-Network/dev-3Tier-app/Resource
  dev3Tierappfromdev3TierNetworkdev3Tierinternal4DB6F1EB8080F9BFB40F:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from dev3TierNetworkdev3Tierinternal4DB6F1EB:8080
      FromPort: 8080
      GroupId:
        Fn::GetAtt:
          - dev3TierappB3CC3F8F
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - dev3TierinternalF413AEF5
          - GroupId
      ToPort: 8080
    Metadata:
      aws:cdk:path: dev-3Tier-Network/dev-3Tier-app/from
        dev3TierNetworkdev3Tierinternal4DB6F1EB:8080
  dev3TierdbB46B52AD:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dev-3Tier-Network/dev-3Tier-db
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        []
      Tags:
        - Key: Name
          Value: dev-3Tier-db
      VpcId:
        Ref: VPCB9E5F0B4
    Metadata:
      aws:cdk:path: dev-3Tier-Network/dev-3Tier-db/Resource
  dev3Tierdbfromdev3TierNetworkdev3TierappEDA2B38E54326EC39EF9:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from dev3TierNetworkdev3TierappEDA2B38E:5432
      FromPort: 5432
      GroupId:
        Fn::GetAtt:
          - dev3TierdbB46B52AD
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - dev3TierappB3CC3F8F
          - GroupId
      ToPort: 5432
    Metadata:
      aws:cdk:path: dev-3Tier-Network/dev-3Tier-db/from
        dev3TierNetworkdev3TierappEDA2B38E:5432
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.21.0,@aws-cdk/assets=0.21.0,@aws-cdk/aws-autoscaling=0.21.0,@aws-cdk/aws-autoscaling-common=0.21.0,@aws-cdk/aws-cloudformation=0.21.0,@aws-cdk/aws-cloudfront=0.21.0,@aws-cdk/aws-cloudwatch=0.21.0,@aws-cdk/aws-codedeploy-api=0.21.0,@aws-cdk/aws-codepipeline-api=0.21.0,@aws-cdk/aws-ec2=0.21.0,@aws-cdk/aws-elasticloadbalancingv2=0.21.0,@aws-cdk/aws-events=0.21.0,@aws-cdk/aws-iam=0.21.0,@aws-cdk/aws-kms=0.21.0,@aws-cdk/aws-lambda=0.21.0,@aws-cdk/aws-s3=0.21.0,@aws-cdk/aws-s3-deployment=0.21.0,@aws-cdk/aws-s3-notifications=0.21.0,@aws-cdk/aws-sqs=0.21.0,@aws-cdk/cdk=0.21.0,@aws-cdk/cx-api=0.21.0,jsii-runtime=node.js/v10.14.1
Outputs:
  VPCPublicSubnetIDs428979F9:
    Value:
      Fn::Join:
        - ","
        - - Ref: VPCwebSubnet1Subnet70A8869C
          - Ref: VPCwebSubnet2SubnetA89FD16F
    Export:
      Name: dev-3Tier-Network:VPCPublicSubnetIDs428979F9
  VPCPrivateSubnetIDsA55EE406:
    Value:
      Fn::Join:
        - ","
        - - Ref: VPCappSubnet1SubnetCDCE8516
          - Ref: VPCappSubnet2Subnet12EE3759
    Export:
      Name: dev-3Tier-Network:VPCPrivateSubnetIDsA55EE406
  VPCIsolatedSubnetIDs0BAB2DBD:
    Value:
      Fn::Join:
        - ","
        - - Ref: VPCdbSubnet1SubnetC7C1BE50
          - Ref: VPCdbSubnet2Subnet4D0CD5E3
    Export:
      Name: dev-3Tier-Network:VPCIsolatedSubnetIDs0BAB2DBD
  VPCVpcId2F75874A:
    Value:
      Ref: VPCB9E5F0B4
    Export:
      Name: dev-3Tier-Network:VPCVpcId2F75874A
  dev3TierinternetSecurityGroupIdE64FE869:
    Value:
      Fn::GetAtt:
        - dev3TierinternetC5AC4D78
        - GroupId
    Export:
      Name: dev-3Tier-Network:dev3TierinternetSecurityGroupIdE64FE869
  dev3TierwebSecurityGroupId830DAA5E:
    Value:
      Fn::GetAtt:
        - dev3Tierweb3038E85D
        - GroupId
    Export:
      Name: dev-3Tier-Network:dev3TierwebSecurityGroupId830DAA5E
  dev3TierinternalSecurityGroupId664C114B:
    Value:
      Fn::GetAtt:
        - dev3TierinternalF413AEF5
        - GroupId
    Export:
      Name: dev-3Tier-Network:dev3TierinternalSecurityGroupId664C114B
  dev3TierappSecurityGroupId8ADD0104:
    Value:
      Fn::GetAtt:
        - dev3TierappB3CC3F8F
        - GroupId
    Export:
      Name: dev-3Tier-Network:dev3TierappSecurityGroupId8ADD0104
  dev3TierdbSecurityGroupIdC60AF894:
    Value:
      Fn::GetAtt:
        - dev3TierdbB46B52AD
        - GroupId
    Export:
      Name: dev-3Tier-Network:dev3TierdbSecurityGroupIdC60AF894
